export const CATEGORIAS = [
  'Robo',
  'Hurto',
  'Asalto',
  'Violencia doméstica',
  'Violencia de género',
  'Violación',
  'Intento de secuestro',
  'Secuestro',
  'Persona desaparecida',
  'Acoso callejero',
  'Amenazas',
  'Homicidio',
  'Pelea callejera',
  'Incendio',
  'Explosión',
  'Accidente de tránsito',
  'Choque con fuga',
  'Conducción peligrosa',
  'Venta de drogas',
  'Consumo de drogas en vía pública',
  'Portación de armas',
  'Tiroteo',
  'Vandalismo',
  'Daños a propiedad pública/privada',
  'Ruido excesivo',
  'Disturbios',
  'Manifestación violenta',
  'Maltrato animal',
  'Abandono de menores',
  'Emergencia médica',
  'Emergencia natural (inundación, derrumbe, etc.)',
  'Otros',
]
